### ISSUE TITLE
Make site responsive 

### ISSUE THREAD

**Issue by Pipe-to-Grep** [xeleration/memerator#67]
Change css to use measurements like em and rem to respond to mobile platforms

**Comment by CameronSamuels** [comment]
Thanks! But do you mean to respond to desktop. It works perfectly fine on mobile. Normally people say responsive to mobile not to desktop.

**Comment by Pipe-to-Grep** [comment]
Responsive to mobile. Some things are a little off sometimes.

**Comment by CameronSamuels** [comment]
By the way, `em` and `rem` aren't for responding to screen sizes. The values you can are `vh`, `vw`, and `%`.

**Comment by CameronSamuels** [comment]
This in my opinion is fine on both platforms. And em and `rem` won’t be responsive. I will not fix this issue.
